echo "------------------------------------------"
echo "Welcome. This is your SYSTEM BOT reporting."
echo "------------------------------------------"
echo "Things I can do."
echo "---------------------"
echo "|1.File Management  |"
echo "|2.Firefox Search   |"
echo "|3.System info      |"
echo "|4.Whatsapp chat    |"
echo "|5.System handling  |"
echo "|6.Date and Time    |"
echo "|7.Exit             |"
echo "---------------------"
echo "Select one option which u want me to do"
read ch
